FROM lyrasis/archivesspace:base
MAINTAINER Mark Cooper <mark.c.cooper@outlook.com>

ENV ARCHIVESSPACE_VERSION={{ archivesspace_version }}

ENV ARCHIVESSPACE_URL={{ archivesspace_url }} \
  ARCHIVESSPACE_DB_TYPE=demo \
  ARCHIVESSPACE_DB_HOST_TYPE=internal \
  ARCHIVESSPACE_DB_NAME=archivesspace \
  ARCHIVESSPACE_DB_USER=archivesspace \
  ARCHIVESSPACE_DB_PASS=archivesspace

RUN wget $ARCHIVESSPACE_URL
RUN unzip archivesspace-v$ARCHIVESSPACE_VERSION.zip
RUN wget http://central.maven.org/maven2/mysql/mysql-connector-java/{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}.jar

# FINALIZE SETUP
RUN rm -rf /archivesspace/plugins/*
RUN cp /mysql-connector-java-{{ mysql_connector_version }}.jar /archivesspace/lib/
ADD setup.sh /setup.sh
RUN chmod u+x /*.sh
ADD launcher_rc.rb /archivesspace/launcher_rc.rb

EXPOSE 8080 8081 8089 8090

CMD ["/setup.sh"]
